import type { Metadata } from "next";
import { Cormorant_Garamond, Cormorant_Infant } from "next/font/google";
import "./globals.css";
import AppTransitionShell from "../components/AppTransitionShell";

const scrollText = Cormorant_Garamond({
  variable: "--font-scroll-text",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

const scrollHeading = Cormorant_Infant({
  variable: "--font-scroll-heading",
  subsets: ["latin"],
  display: "swap",
  weight: ["500", "600", "700"],
});

export const metadata: Metadata = {
  title: "miro.io",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full w-full m-0 p-0">
      <body className={`${scrollText.variable} ${scrollHeading.variable} h-full w-full m-0 p-0 bg-[#FBDDB5]`}>
        <AppTransitionShell>{children}</AppTransitionShell>
      </body>
    </html>
  );
}
